//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTemplate.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageText {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageText() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ProjectTemplate.Core.Resources.MessageText", typeof(MessageText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AnUnknownFailureHasOccurred {
            get {
                return ResourceManager.GetString("AnUnknownFailureHasOccurred", resourceCulture);
            }
        }
        
        public static string AUserWithThisLoginAlreadyExists {
            get {
                return ResourceManager.GetString("AUserWithThisLoginAlreadyExists", resourceCulture);
            }
        }
        
        public static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        public static string IsAlreadyTaken {
            get {
                return ResourceManager.GetString("IsAlreadyTaken", resourceCulture);
            }
        }
        
        public static string IsAlreadyTakenForFeminine {
            get {
                return ResourceManager.GetString("IsAlreadyTakenForFeminine", resourceCulture);
            }
        }
        
        public static string IsInvalid {
            get {
                return ResourceManager.GetString("IsInvalid", resourceCulture);
            }
        }
        
        public static string IsInvalidForFeminine {
            get {
                return ResourceManager.GetString("IsInvalidForFeminine", resourceCulture);
            }
        }
        
        public static string LockoutIsNotEnabledForThisUser {
            get {
                return ResourceManager.GetString("LockoutIsNotEnabledForThisUser", resourceCulture);
            }
        }
        
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        public static string PasswordMustBeAtLeast {
            get {
                return ResourceManager.GetString("PasswordMustBeAtLeast", resourceCulture);
            }
        }
        
        public static string PasswordsMustHaveAtLeastOneDigit {
            get {
                return ResourceManager.GetString("PasswordsMustHaveAtLeastOneDigit", resourceCulture);
            }
        }
        
        public static string PasswordsMustHaveAtLeastOneLowercase {
            get {
                return ResourceManager.GetString("PasswordsMustHaveAtLeastOneLowercase", resourceCulture);
            }
        }
        
        public static string PasswordsMustHaveAtLeastOneNonAlphanumericCharacter {
            get {
                return ResourceManager.GetString("PasswordsMustHaveAtLeastOneNonAlphanumericCharacter", resourceCulture);
            }
        }
        
        public static string PasswordsMustHaveAtLeastOneUppercase {
            get {
                return ResourceManager.GetString("PasswordsMustHaveAtLeastOneUppercase", resourceCulture);
            }
        }
        
        public static string PleaseFixTheFollowingErrors {
            get {
                return ResourceManager.GetString("PleaseFixTheFollowingErrors", resourceCulture);
            }
        }
        
        public static string PleaseWritePassword {
            get {
                return ResourceManager.GetString("PleaseWritePassword", resourceCulture);
            }
        }
        
        public static string UserAlreadyHasAPasswordSet {
            get {
                return ResourceManager.GetString("UserAlreadyHasAPasswordSet", resourceCulture);
            }
        }
        
        public static string UserAlreadyInRole {
            get {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }
        
        public static string UserIsNotInRole {
            get {
                return ResourceManager.GetString("UserIsNotInRole", resourceCulture);
            }
        }
        
        public static string UserNameIsInvalid {
            get {
                return ResourceManager.GetString("UserNameIsInvalid", resourceCulture);
            }
        }
        
        public static string EmailIsAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailIsAlreadyTaken", resourceCulture);
            }
        }
        
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        public static string InvlaidUserName {
            get {
                return ResourceManager.GetString("InvlaidUserName", resourceCulture);
            }
        }
        
        public static string PasswordMustUseAtLeastDifferenctCharacters {
            get {
                return ResourceManager.GetString("PasswordMustUseAtLeastDifferenctCharacters", resourceCulture);
            }
        }
        
        public static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        public static string RoleIsAlreadyTaken {
            get {
                return ResourceManager.GetString("RoleIsAlreadyTaken", resourceCulture);
            }
        }
        
        public static string UserNameIsAlreadyTaken {
            get {
                return ResourceManager.GetString("UserNameIsAlreadyTaken", resourceCulture);
            }
        }
        
        public static string YouCannotDeleteTheItemBecauseItIsLinkedWithOtherItems {
            get {
                return ResourceManager.GetString("YouCannotDeleteTheItemBecauseItIsLinkedWithOtherItems", resourceCulture);
            }
        }
    }
}
